name: Test Yarn Cache Action

on:
  pull_request:
    paths: [actions/yarn-cache/**]

env:
  CACHE_PATH: |
    ~/.cache
    test/actions/yarn-cache/.yarn/unplugged
    test/actions/yarn-cache/.yarn/install-state.gz
  WORKING_DIR: ./test/actions/yarn-cache

jobs:
  first-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: test/actions/yarn-cache/.nvmrc
      - run: corepack enable
      - uses: ./actions/yarn-cache
        with:
          cache_path: ${{ env.CACHE_PATH }}
          working-directory: ${{ env.WORKING_DIR }}

  second-cache:
    needs: [first-cache]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: test/actions/yarn-cache/.nvmrc
      - run: corepack enable
      - uses: ./actions/yarn-cache
        with:
          cache_path: ${{ env.CACHE_PATH }}
          working-directory: ${{ env.WORKING_DIR }}
