name: Test NPM Cache Action

on:
  pull_request:
    paths: [actions/npm-cache/**]

env:
  CACHE_PATH: test/actions/npm-cache/node_modules
  WORKING_DIR: test/actions/npm-cache

jobs:
  first-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: test/actions/npm-cache/.nvmrc
      - uses: ./actions/npm-cache
        with:
          cache_path: ${{ env.CACHE_PATH }}
          working-directory: ${{ env.WORKING_DIR }}

  second-cache:
    needs: [first-cache]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: test/actions/npm-cache/.nvmrc
      - uses: ./actions/npm-cache
        with:
          cache_path: ${{ env.CACHE_PATH }}
          working-directory: ${{ env.WORKING_DIR }}
